### ISSUE TITLE
make cache duration configurable via ENV 

### ISSUE THREAD

**Issue by davehorton** [jambonz/speech-utils#10]
Currently [tts files are stored in cache for 24 hours](https://github.com/jambonz/speech-utils/blob/5a7c3cf11b7f34ca124c615d7ed145d1d2aa002b/lib/synth-audio.js#L35).  We should have an env like JAMBONES_TTS_CACHE_DURATION_MINS that allows this to be overridden.

**Comment by xquanluu** [comment]
closed as PR is merged
