### ISSUE TITLE
Update azure speech utils to 1.33.1

### ISSUE THREAD

**Issue by davehorton** [jambonz/speech-utils#45]
This [release](https://www.npmjs.com/package/microsoft-cognitiveservices-speech-sdk) appears to introduce some new voices and other features we should support

https://learn.microsoft.com/en-us/azure/ai-services/speech-service/releasenotes?tabs=text-to-speech

Lets test out the new voices, and also test the "personal voice" feature.

**Comment by xquanluu** [comment]
Hi @davehorton 

Follow this document: https://learn.microsoft.com/en-us/azure/ai-services/speech-service/personal-voice-overview, bellow is SSML for playing personal voice.

Do you know where I can get name='PhoenixV2Neural' and speakerProfileId='your speaker profile ID here'?

`<speak version='1.0' xmlns='http://www.w3.org/2001/10/synthesis' xmlns:mstts='http://www.w3.org/2001/mstts' xml:lang='en-US'>
    <voice xml:lang='en-US' xml:gender='Male' name='PhoenixV2Neural'> 
    <mstts:ttsembedding speakerProfileId='your speaker profile ID here'> 
    I'm happy to hear that you find me amazing and that I have made your trip planning easier and more fun. 我很高兴听到你觉得我很了不起，我让你的旅行计划更轻松、更有趣。Je suis heureux d'apprendre que vous me trouvez incroyable et que j'ai rendu la planification de votre voyage plus facile et plus amusante.  
    </mstts:ttsembedding> 
    </voice> 
</speak> `
